import type { Item } from '@/types';

export const initialItems: Item[] = [
  {
    id: '1',
    name: 'Classic White Tee',
    type: 'Shirt',
    description: 'A timeless classic, this white t-shirt is made from 100% premium cotton. It offers a comfortable fit and a versatile look that pairs well with anything.',
    coverImage: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'white t-shirt',
    additionalImages: ['https://placehold.co/600x401.png', 'https://placehold.co/600x402.png'],
  },
  {
    id: '2',
    name: 'Denim Jeans',
    type: 'Pant',
    description: 'Stylish and durable denim jeans. Perfect for casual outings and everyday wear. Features a slim-fit design with a classic five-pocket style.',
    coverImage: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'denim jeans',
    additionalImages: ['https://placehold.co/601x400.png', 'https://placehold.co/602x400.png'],
  },
  {
    id: '3',
    name: 'Leather Sneakers',
    type: 'Shoes',
    description: 'Comfortable and sleek leather sneakers. These shoes are designed for both style and comfort, with a cushioned insole and a durable rubber outsole.',
    coverImage: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'leather sneakers',
    additionalImages: ['https://placehold.co/600x400.png', 'https://placehold.co/600x400.png'],
  },
  {
    id: '4',
    name: 'Running Shorts',
    type: 'Sports Gear',
    description: 'Lightweight and breathable running shorts for your workout sessions. Made with moisture-wicking fabric to keep you dry and comfortable.',
    coverImage: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'running shorts',
    additionalImages: ['https://placehold.co/600x400.png', 'https://placehold.co/600x400.png'],
  },
   {
    id: '5',
    name: 'Aviator Sunglasses',
    type: 'Accessory',
    description: 'Classic aviator sunglasses with polarized lenses. Provides 100% UV protection while adding a cool factor to any outfit.',
    coverImage: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'aviator sunglasses',
    additionalImages: ['https://placehold.co/600x400.png', 'https://placehold.co/600x400.png'],
  },
   {
    id: '6',
    name: 'Blue Hoodie',
    type: 'Shirt',
    description: 'A cozy blue hoodie made from a soft cotton blend. Features a drawstring hood and a large front pocket. Ideal for cool weather.',
    coverImage: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'blue hoodie',
    additionalImages: ['https://placehold.co/600x400.png', 'https://placehold.co/600x400.png'],
  },
  {
    id: '7',
    name: 'Khaki Chinos',
    type: 'Pant',
    description: 'Versatile khaki chinos that can be dressed up or down. Made from a comfortable stretch cotton twill.',
    coverImage: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'khaki pants',
    additionalImages: ['https://placehold.co/600x400.png', 'https://placehold.co/600x400.png'],
  },
  {
    id: '8',
    name: 'Leather Belt',
    type: 'Accessory',
    description: 'A classic brown leather belt with a simple silver buckle. The perfect finishing touch for any outfit.',
    coverImage: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'leather belt',
    additionalImages: ['https://placehold.co/600x400.png'],
  },
  {
    id: '9',
    name: 'Chronograph Watch',
    type: 'Accessory',
    description: 'A sophisticated chronograph watch with a stainless steel strap and a dark blue face. Water-resistant and perfect for both formal and casual occasions.',
    coverImage: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'chronograph watch',
    additionalImages: ['https://placehold.co/600x400.png'],
  },
  {
    id: '10',
    name: 'Canvas Backpack',
    type: 'Accessory',
    description: 'A durable and spacious canvas backpack, perfect for daily commutes or weekend trips. Features multiple compartments and padded laptop sleeve.',
    coverImage: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'canvas backpack',
    additionalImages: ['https://placehold.co/600x400.png'],
  },
  {
    id: '11',
    name: 'Linen Dress Shirt',
    type: 'Shirt',
    description: 'A breathable linen dress shirt in a light-blue color. Ideal for warm weather, offering a sharp yet relaxed look.',
    coverImage: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'dress shirt',
    additionalImages: ['https://placehold.co/600x400.png'],
  },
  {
    id: '12',
    name: 'Suede Loafers',
    type: 'Shoes',
    description: 'Classic suede loafers in a versatile tan color. Comfortable for all-day wear and easy to pair with chinos or jeans.',
    coverImage: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'suede loafers',
    additionalImages: ['https://placehold.co/600x400.png'],
  },
  {
    id: '13',
    name: 'Black Leather Jacket',
    type: 'Shirt',
    description: 'A classic black leather jacket. Perfect for a cool, edgy look. Features a front zip and multiple pockets.',
    coverImage: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'leather jacket',
    additionalImages: ['https://placehold.co/600x400.png'],
  },
  {
    id: '14',
    name: 'Wool Scarf',
    type: 'Accessory',
    description: 'A soft and warm wool scarf in a neutral grey color. Perfect for staying warm in style during colder months.',
    coverImage: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'wool scarf',
    additionalImages: ['https://placehold.co/600x400.png'],
  },
  {
    id: '15',
    name: 'Grey Sweatpants',
    type: 'Pant',
    description: 'Comfortable grey sweatpants for lounging or a casual day out. Made from a soft cotton blend with a relaxed fit.',
    coverImage: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'grey sweatpants',
    additionalImages: ['https://placehold.co/600x400.png'],
  },
  {
    id: '16',
    name: 'Hiking Boots',
    type: 'Shoes',
    description: 'Durable and waterproof hiking boots designed for tough terrains. Provides excellent support and traction.',
    coverImage: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'hiking boots',
    additionalImages: ['https://placehold.co/600x400.png'],
  },
];
